### ISSUE TITLE
No gif found

### ISSUE THREAD

**Issue by fancibleunicorn** [Ondayko14/coding-with-cocktails#10]
Error message occurs when search criteria (drink name) doesn't return any gif's.

**Comment by fancibleunicorn** [comment]
![image](https://user-images.githubusercontent.com/70110908/99120561-11aaea00-25c9-11eb-98ff-ee217d5853b9.png)

example of drink that causes this (Melya)

**Comment by Ondayko14** [comment]
Error now displays an image of bender and a turtle instead of nothing
